# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'healthApplicationMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 951, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.nursePushButton = QtWidgets.QPushButton(self.mainPage)
        self.nursePushButton.setGeometry(QtCore.QRect(260, 140, 461, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.nursePushButton.setFont(font)
        self.nursePushButton.setObjectName("nursePushButton")
        self.titleLabel = QtWidgets.QLabel(self.mainPage)
        self.titleLabel.setGeometry(QtCore.QRect(10, 0, 941, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.doctorPushButton = QtWidgets.QPushButton(self.mainPage)
        self.doctorPushButton.setGeometry(QtCore.QRect(260, 310, 461, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.doctorPushButton.setFont(font)
        self.doctorPushButton.setObjectName("doctorPushButton")
        self.stackedWidget.addWidget(self.mainPage)
        self.contactInfoPage = QtWidgets.QWidget()
        self.contactInfoPage.setObjectName("contactInfoPage")
        self.contactInfoLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.contactInfoLabel.setGeometry(QtCore.QRect(20, 20, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.contactInfoLabel.setFont(font)
        self.contactInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contactInfoLabel.setObjectName("contactInfoLabel")
        self.firstNameLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.firstNameLabel.setGeometry(QtCore.QRect(50, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.firstNameLabel.setFont(font)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.firstNameInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.firstNameInput.setGeometry(QtCore.QRect(300, 160, 601, 41))
        self.firstNameInput.setObjectName("firstNameInput")
        self.middleNameLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.middleNameLabel.setGeometry(QtCore.QRect(50, 210, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.middleNameLabel.setFont(font)
        self.middleNameLabel.setObjectName("middleNameLabel")
        self.middleNameInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.middleNameInput.setGeometry(QtCore.QRect(300, 210, 601, 41))
        self.middleNameInput.setObjectName("middleNameInput")
        self.lastNameLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.lastNameLabel.setGeometry(QtCore.QRect(50, 260, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.lastNameInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.lastNameInput.setGeometry(QtCore.QRect(300, 260, 601, 41))
        self.lastNameInput.setObjectName("lastNameInput")
        self.phoneNumberLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.phoneNumberLabel.setGeometry(QtCore.QRect(50, 310, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.phoneNumberLabel.setFont(font)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.phoneNumberInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.phoneNumberInput.setGeometry(QtCore.QRect(300, 310, 601, 41))
        self.phoneNumberInput.setObjectName("phoneNumberInput")
        self.emailLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.emailLabel.setGeometry(QtCore.QRect(50, 360, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.emailInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.emailInput.setGeometry(QtCore.QRect(300, 360, 601, 41))
        self.emailInput.setObjectName("emailInput")
        self.acceptInfoButton = QtWidgets.QPushButton(self.contactInfoPage)
        self.acceptInfoButton.setGeometry(QtCore.QRect(600, 430, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.acceptInfoButton.setFont(font)
        self.acceptInfoButton.setObjectName("acceptInfoButton")
        self.cancelButton = QtWidgets.QPushButton(self.contactInfoPage)
        self.cancelButton.setGeometry(QtCore.QRect(370, 430, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.stackedWidget.addWidget(self.contactInfoPage)
        self.insuranceInfoPage = QtWidgets.QWidget()
        self.insuranceInfoPage.setObjectName("insuranceInfoPage")
        self.insuranceInfoLabel = QtWidgets.QLabel(self.insuranceInfoPage)
        self.insuranceInfoLabel.setGeometry(QtCore.QRect(20, 10, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.insuranceInfoLabel.setFont(font)
        self.insuranceInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.insuranceInfoLabel.setObjectName("insuranceInfoLabel")
        self.middleNameLabel_2 = QtWidgets.QLabel(self.insuranceInfoPage)
        self.middleNameLabel_2.setGeometry(QtCore.QRect(40, 180, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.middleNameLabel_2.setFont(font)
        self.middleNameLabel_2.setObjectName("middleNameLabel_2")
        self.lastNameInput_2 = QtWidgets.QTextEdit(self.insuranceInfoPage)
        self.lastNameInput_2.setGeometry(QtCore.QRect(290, 230, 601, 41))
        self.lastNameInput_2.setObjectName("lastNameInput_2")
        self.firstNameLabel_2 = QtWidgets.QLabel(self.insuranceInfoPage)
        self.firstNameLabel_2.setGeometry(QtCore.QRect(40, 130, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.firstNameLabel_2.setFont(font)
        self.firstNameLabel_2.setObjectName("firstNameLabel_2")
        self.lastNameLabel_2 = QtWidgets.QLabel(self.insuranceInfoPage)
        self.lastNameLabel_2.setGeometry(QtCore.QRect(40, 230, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lastNameLabel_2.setFont(font)
        self.lastNameLabel_2.setObjectName("lastNameLabel_2")
        self.firstNameInput_2 = QtWidgets.QTextEdit(self.insuranceInfoPage)
        self.firstNameInput_2.setGeometry(QtCore.QRect(290, 130, 601, 41))
        self.firstNameInput_2.setObjectName("firstNameInput_2")
        self.middleNameInput_2 = QtWidgets.QTextEdit(self.insuranceInfoPage)
        self.middleNameInput_2.setGeometry(QtCore.QRect(290, 180, 601, 41))
        self.middleNameInput_2.setObjectName("middleNameInput_2")
        self.stackedWidget.addWidget(self.insuranceInfoPage)
        self.healthConcernsPage = QtWidgets.QWidget()
        self.healthConcernsPage.setObjectName("healthConcernsPage")
        self.healthConcernsLabel = QtWidgets.QLabel(self.healthConcernsPage)
        self.healthConcernsLabel.setGeometry(QtCore.QRect(10, 10, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.healthConcernsLabel.setFont(font)
        self.healthConcernsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.healthConcernsLabel.setObjectName("healthConcernsLabel")
        self.stackedWidget.addWidget(self.healthConcernsPage)
        self.contactNursePage = QtWidgets.QWidget()
        self.contactNursePage.setObjectName("contactNursePage")
        self.contactNurseLabel = QtWidgets.QLabel(self.contactNursePage)
        self.contactNurseLabel.setGeometry(QtCore.QRect(30, 20, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.contactNurseLabel.setFont(font)
        self.contactNurseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contactNurseLabel.setObjectName("contactNurseLabel")
        self.nextAvailButton = QtWidgets.QPushButton(self.contactNursePage)
        self.nextAvailButton.setGeometry(QtCore.QRect(120, 240, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nextAvailButton.setFont(font)
        self.nextAvailButton.setObjectName("nextAvailButton")
        self.scheduleACallButton = QtWidgets.QPushButton(self.contactNursePage)
        self.scheduleACallButton.setGeometry(QtCore.QRect(470, 240, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.scheduleACallButton.setFont(font)
        self.scheduleACallButton.setObjectName("scheduleACallButton")
        self.stackedWidget.addWidget(self.contactNursePage)
        self.scheduleDoctorAppointmentPage = QtWidgets.QWidget()
        self.scheduleDoctorAppointmentPage.setObjectName("scheduleDoctorAppointmentPage")
        self.scheduleTitle = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.scheduleTitle.setGeometry(QtCore.QRect(30, 20, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.scheduleTitle.setFont(font)
        self.scheduleTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.scheduleTitle.setObjectName("scheduleTitle")
        self.typeAppointment = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.typeAppointment.setGeometry(QtCore.QRect(60, 140, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.typeAppointment.setFont(font)
        self.typeAppointment.setObjectName("typeAppointment")
        self.appointmentTypeComboBox = QtWidgets.QComboBox(self.scheduleDoctorAppointmentPage)
        self.appointmentTypeComboBox.setGeometry(QtCore.QRect(400, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.appointmentTypeComboBox.setFont(font)
        self.appointmentTypeComboBox.setObjectName("appointmentTypeComboBox")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentCalendar = QtWidgets.QCalendarWidget(self.scheduleDoctorAppointmentPage)
        self.appointmentCalendar.setGeometry(QtCore.QRect(600, 150, 312, 183))
        self.appointmentCalendar.setMinimumDate(QtCore.QDate(2020, 10, 3))
        self.appointmentCalendar.setGridVisible(False)
        self.appointmentCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.appointmentCalendar.setObjectName("appointmentCalendar")
        self.dateSelectorLabel = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.dateSelectorLabel.setGeometry(QtCore.QRect(60, 210, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dateSelectorLabel.setFont(font)
        self.dateSelectorLabel.setObjectName("dateSelectorLabel")
        self.timeSelectorLabel = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.timeSelectorLabel.setGeometry(QtCore.QRect(60, 280, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeSelectorLabel.setFont(font)
        self.timeSelectorLabel.setObjectName("timeSelectorLabel")
        self.dateEdit = QtWidgets.QDateEdit(self.scheduleDoctorAppointmentPage)
        self.dateEdit.setGeometry(QtCore.QRect(400, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.scheduleDoctorAppointmentPage)
        self.timeEdit.setGeometry(QtCore.QRect(400, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.acceptAppointmentButton = QtWidgets.QPushButton(self.scheduleDoctorAppointmentPage)
        self.acceptAppointmentButton.setGeometry(QtCore.QRect(360, 350, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.acceptAppointmentButton.setFont(font)
        self.acceptAppointmentButton.setObjectName("acceptAppointmentButton")
        self.cancelAppointmentButton = QtWidgets.QPushButton(self.scheduleDoctorAppointmentPage)
        self.cancelAppointmentButton.setGeometry(QtCore.QRect(130, 350, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cancelAppointmentButton.setFont(font)
        self.cancelAppointmentButton.setObjectName("cancelAppointmentButton")
        self.stackedWidget.addWidget(self.scheduleDoctorAppointmentPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.appointmentTypeComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nursePushButton.setText(_translate("MainWindow", "Nurse Consult"))
        self.titleLabel.setText(_translate("MainWindow", "Medical Appointment Helper"))
        self.doctorPushButton.setText(_translate("MainWindow", "Doctor Consult"))
        self.contactInfoLabel.setText(_translate("MainWindow", "Enter your Contact Information"))
        self.firstNameLabel.setText(_translate("MainWindow", "First Name"))
        self.middleNameLabel.setText(_translate("MainWindow", "Middle Name"))
        self.lastNameLabel.setText(_translate("MainWindow", "Last Name"))
        self.phoneNumberLabel.setText(_translate("MainWindow", "Phone"))
        self.emailLabel.setText(_translate("MainWindow", "Email"))
        self.acceptInfoButton.setText(_translate("MainWindow", "Ok"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.insuranceInfoLabel.setText(_translate("MainWindow", "Enter your Insurance Information"))
        self.middleNameLabel_2.setText(_translate("MainWindow", "Middle Name"))
        self.firstNameLabel_2.setText(_translate("MainWindow", "First Name"))
        self.lastNameLabel_2.setText(_translate("MainWindow", "Last Name"))
        self.healthConcernsLabel.setText(_translate("MainWindow", "Select your symptoms"))
        self.contactNurseLabel.setText(_translate("MainWindow", "Contact a Nurse"))
        self.nextAvailButton.setText(_translate("MainWindow", "Next Available Nurse"))
        self.scheduleACallButton.setText(_translate("MainWindow", "Schedule a Call with a Nurse"))
        self.scheduleTitle.setText(_translate("MainWindow", "Schedule a Doctor\'s Appointment"))
        self.typeAppointment.setText(_translate("MainWindow", "Select Appointment Type"))
        self.appointmentTypeComboBox.setCurrentText(_translate("MainWindow", "Select"))
        self.appointmentTypeComboBox.setItemText(0, _translate("MainWindow", "Select"))
        self.appointmentTypeComboBox.setItemText(1, _translate("MainWindow", "Physical"))
        self.appointmentTypeComboBox.setItemText(2, _translate("MainWindow", "Sick Visit"))
        self.appointmentTypeComboBox.setItemText(3, _translate("MainWindow", "Other"))
        self.dateSelectorLabel.setText(_translate("MainWindow", "Select Appointment Date"))
        self.timeSelectorLabel.setText(_translate("MainWindow", "Select Appointment Time"))
        self.acceptAppointmentButton.setText(_translate("MainWindow", "Ok"))
        self.cancelAppointmentButton.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

