# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'healthApplicationMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 951, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.nursePushButton = QtWidgets.QPushButton(self.mainPage)
        self.nursePushButton.setGeometry(QtCore.QRect(260, 140, 461, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.nursePushButton.setFont(font)
        self.nursePushButton.setObjectName("nursePushButton")
        self.titleLabel = QtWidgets.QLabel(self.mainPage)
        self.titleLabel.setGeometry(QtCore.QRect(10, 0, 941, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.doctorPushButton = QtWidgets.QPushButton(self.mainPage)
        self.doctorPushButton.setGeometry(QtCore.QRect(260, 310, 461, 131))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.doctorPushButton.setFont(font)
        self.doctorPushButton.setObjectName("doctorPushButton")
        self.stackedWidget.addWidget(self.mainPage)
        self.contactInfoPage = QtWidgets.QWidget()
        self.contactInfoPage.setObjectName("contactInfoPage")
        self.contactInfoLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.contactInfoLabel.setGeometry(QtCore.QRect(20, 20, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.contactInfoLabel.setFont(font)
        self.contactInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contactInfoLabel.setObjectName("contactInfoLabel")
        self.firstNameLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.firstNameLabel.setGeometry(QtCore.QRect(50, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.firstNameLabel.setFont(font)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.firstNameInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.firstNameInput.setGeometry(QtCore.QRect(300, 160, 601, 41))
        self.firstNameInput.setObjectName("firstNameInput")
        self.middleNameLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.middleNameLabel.setGeometry(QtCore.QRect(50, 210, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.middleNameLabel.setFont(font)
        self.middleNameLabel.setObjectName("middleNameLabel")
        self.middleNameInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.middleNameInput.setGeometry(QtCore.QRect(300, 210, 601, 41))
        self.middleNameInput.setObjectName("middleNameInput")
        self.lastNameLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.lastNameLabel.setGeometry(QtCore.QRect(50, 260, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.lastNameInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.lastNameInput.setGeometry(QtCore.QRect(300, 260, 601, 41))
        self.lastNameInput.setObjectName("lastNameInput")
        self.phoneNumberLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.phoneNumberLabel.setGeometry(QtCore.QRect(50, 310, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.phoneNumberLabel.setFont(font)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.phoneNumberInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.phoneNumberInput.setGeometry(QtCore.QRect(300, 310, 601, 41))
        self.phoneNumberInput.setObjectName("phoneNumberInput")
        self.emailLabel = QtWidgets.QLabel(self.contactInfoPage)
        self.emailLabel.setGeometry(QtCore.QRect(50, 360, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.emailInput = QtWidgets.QTextEdit(self.contactInfoPage)
        self.emailInput.setGeometry(QtCore.QRect(300, 360, 601, 41))
        self.emailInput.setObjectName("emailInput")
        self.acceptInfoButton = QtWidgets.QPushButton(self.contactInfoPage)
        self.acceptInfoButton.setGeometry(QtCore.QRect(600, 430, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.acceptInfoButton.setFont(font)
        self.acceptInfoButton.setObjectName("acceptInfoButton")
        self.cancelButton = QtWidgets.QPushButton(self.contactInfoPage)
        self.cancelButton.setGeometry(QtCore.QRect(370, 430, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.stackedWidget.addWidget(self.contactInfoPage)
        self.insuranceInfoPage = QtWidgets.QWidget()
        self.insuranceInfoPage.setObjectName("insuranceInfoPage")
        self.insuranceInfoLabel = QtWidgets.QLabel(self.insuranceInfoPage)
        self.insuranceInfoLabel.setGeometry(QtCore.QRect(20, 10, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.insuranceInfoLabel.setFont(font)
        self.insuranceInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.insuranceInfoLabel.setObjectName("insuranceInfoLabel")
        self.middleNameLabel_2 = QtWidgets.QLabel(self.insuranceInfoPage)
        self.middleNameLabel_2.setGeometry(QtCore.QRect(40, 180, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.middleNameLabel_2.setFont(font)
        self.middleNameLabel_2.setObjectName("middleNameLabel_2")
        self.lastNameInput_2 = QtWidgets.QTextEdit(self.insuranceInfoPage)
        self.lastNameInput_2.setGeometry(QtCore.QRect(290, 230, 601, 41))
        self.lastNameInput_2.setObjectName("lastNameInput_2")
        self.firstNameLabel_2 = QtWidgets.QLabel(self.insuranceInfoPage)
        self.firstNameLabel_2.setGeometry(QtCore.QRect(40, 130, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.firstNameLabel_2.setFont(font)
        self.firstNameLabel_2.setObjectName("firstNameLabel_2")
        self.lastNameLabel_2 = QtWidgets.QLabel(self.insuranceInfoPage)
        self.lastNameLabel_2.setGeometry(QtCore.QRect(40, 230, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lastNameLabel_2.setFont(font)
        self.lastNameLabel_2.setObjectName("lastNameLabel_2")
        self.firstNameInput_2 = QtWidgets.QTextEdit(self.insuranceInfoPage)
        self.firstNameInput_2.setGeometry(QtCore.QRect(290, 130, 601, 41))
        self.firstNameInput_2.setObjectName("firstNameInput_2")
        self.middleNameInput_2 = QtWidgets.QTextEdit(self.insuranceInfoPage)
        self.middleNameInput_2.setGeometry(QtCore.QRect(290, 180, 601, 41))
        self.middleNameInput_2.setObjectName("middleNameInput_2")
        self.stackedWidget.addWidget(self.insuranceInfoPage)
        self.healthConcernsPage = QtWidgets.QWidget()
        self.healthConcernsPage.setObjectName("healthConcernsPage")
        self.healthConcernsLabel = QtWidgets.QLabel(self.healthConcernsPage)
        self.healthConcernsLabel.setGeometry(QtCore.QRect(10, 10, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.healthConcernsLabel.setFont(font)
        self.healthConcernsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.healthConcernsLabel.setObjectName("healthConcernsLabel")
        self.fatigueCheckBox = QtWidgets.QCheckBox(self.healthConcernsPage)
        self.fatigueCheckBox.setGeometry(QtCore.QRect(90, 130, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fatigueCheckBox.setFont(font)
        self.fatigueCheckBox.setObjectName("fatigueCheckBox")
        self.tightnessCheckBox = QtWidgets.QCheckBox(self.healthConcernsPage)
        self.tightnessCheckBox.setGeometry(QtCore.QRect(90, 160, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tightnessCheckBox.setFont(font)
        self.tightnessCheckBox.setObjectName("tightnessCheckBox")
        self.lightHeadedCheckBox = QtWidgets.QCheckBox(self.healthConcernsPage)
        self.lightHeadedCheckBox.setGeometry(QtCore.QRect(90, 190, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lightHeadedCheckBox.setFont(font)
        self.lightHeadedCheckBox.setObjectName("lightHeadedCheckBox")
        self.heartbeatCheckBox = QtWidgets.QCheckBox(self.healthConcernsPage)
        self.heartbeatCheckBox.setGeometry(QtCore.QRect(90, 220, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.heartbeatCheckBox.setFont(font)
        self.heartbeatCheckBox.setObjectName("heartbeatCheckBox")
        self.anxietyCheckBox = QtWidgets.QCheckBox(self.healthConcernsPage)
        self.anxietyCheckBox.setGeometry(QtCore.QRect(90, 250, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.anxietyCheckBox.setFont(font)
        self.anxietyCheckBox.setObjectName("anxietyCheckBox")
        self.otherCheckBox = QtWidgets.QCheckBox(self.healthConcernsPage)
        self.otherCheckBox.setGeometry(QtCore.QRect(90, 280, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.otherCheckBox.setFont(font)
        self.otherCheckBox.setObjectName("otherCheckBox")
        self.textEdit = QtWidgets.QTextEdit(self.healthConcernsPage)
        self.textEdit.setGeometry(QtCore.QRect(80, 310, 411, 221))
        self.textEdit.setObjectName("textEdit")
        self.nextButton = QtWidgets.QPushButton(self.healthConcernsPage)
        self.nextButton.setGeometry(QtCore.QRect(530, 230, 401, 101))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.stackedWidget.addWidget(self.healthConcernsPage)
        self.contactNursePage = QtWidgets.QWidget()
        self.contactNursePage.setObjectName("contactNursePage")
        self.contactNurseLabel = QtWidgets.QLabel(self.contactNursePage)
        self.contactNurseLabel.setGeometry(QtCore.QRect(30, 20, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.contactNurseLabel.setFont(font)
        self.contactNurseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contactNurseLabel.setObjectName("contactNurseLabel")
        self.nextAvailButton = QtWidgets.QPushButton(self.contactNursePage)
        self.nextAvailButton.setGeometry(QtCore.QRect(120, 240, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nextAvailButton.setFont(font)
        self.nextAvailButton.setObjectName("nextAvailButton")
        self.scheduleACallButton = QtWidgets.QPushButton(self.contactNursePage)
        self.scheduleACallButton.setGeometry(QtCore.QRect(470, 240, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.scheduleACallButton.setFont(font)
        self.scheduleACallButton.setObjectName("scheduleACallButton")
        self.stackedWidget.addWidget(self.contactNursePage)
        self.scheduleDoctorAppointmentPage = QtWidgets.QWidget()
        self.scheduleDoctorAppointmentPage.setObjectName("scheduleDoctorAppointmentPage")
        self.scheduleTitle = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.scheduleTitle.setGeometry(QtCore.QRect(30, 20, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.scheduleTitle.setFont(font)
        self.scheduleTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.scheduleTitle.setObjectName("scheduleTitle")
        self.typeAppointment = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.typeAppointment.setGeometry(QtCore.QRect(60, 140, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.typeAppointment.setFont(font)
        self.typeAppointment.setObjectName("typeAppointment")
        self.appointmentTypeComboBox = QtWidgets.QComboBox(self.scheduleDoctorAppointmentPage)
        self.appointmentTypeComboBox.setGeometry(QtCore.QRect(400, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.appointmentTypeComboBox.setFont(font)
        self.appointmentTypeComboBox.setObjectName("appointmentTypeComboBox")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentTypeComboBox.addItem("")
        self.appointmentCalendar = QtWidgets.QCalendarWidget(self.scheduleDoctorAppointmentPage)
        self.appointmentCalendar.setGeometry(QtCore.QRect(600, 150, 312, 183))
        self.appointmentCalendar.setMinimumDate(QtCore.QDate(2020, 10, 3))
        self.appointmentCalendar.setGridVisible(False)
        self.appointmentCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.appointmentCalendar.setObjectName("appointmentCalendar")
        self.dateSelectorLabel = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.dateSelectorLabel.setGeometry(QtCore.QRect(60, 210, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dateSelectorLabel.setFont(font)
        self.dateSelectorLabel.setObjectName("dateSelectorLabel")
        self.timeSelectorLabel = QtWidgets.QLabel(self.scheduleDoctorAppointmentPage)
        self.timeSelectorLabel.setGeometry(QtCore.QRect(60, 280, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeSelectorLabel.setFont(font)
        self.timeSelectorLabel.setObjectName("timeSelectorLabel")
        self.dateEdit = QtWidgets.QDateEdit(self.scheduleDoctorAppointmentPage)
        self.dateEdit.setGeometry(QtCore.QRect(400, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.scheduleDoctorAppointmentPage)
        self.timeEdit.setGeometry(QtCore.QRect(400, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeEdit.setFont(font)
        self.timeEdit.setMaximumTime(QtCore.QTime(18, 0, 0))
        self.timeEdit.setMinimumTime(QtCore.QTime(8, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.acceptAppointmentButton = QtWidgets.QPushButton(self.scheduleDoctorAppointmentPage)
        self.acceptAppointmentButton.setGeometry(QtCore.QRect(360, 350, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.acceptAppointmentButton.setFont(font)
        self.acceptAppointmentButton.setObjectName("acceptAppointmentButton")
        self.cancelAppointmentButton = QtWidgets.QPushButton(self.scheduleDoctorAppointmentPage)
        self.cancelAppointmentButton.setGeometry(QtCore.QRect(130, 350, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cancelAppointmentButton.setFont(font)
        self.cancelAppointmentButton.setObjectName("cancelAppointmentButton")
        self.stackedWidget.addWidget(self.scheduleDoctorAppointmentPage)
        self.callNursePage = QtWidgets.QWidget()
        self.callNursePage.setObjectName("callNursePage")
        self.callNurseButton = QtWidgets.QPushButton(self.callNursePage)
        self.callNurseButton.setGeometry(QtCore.QRect(340, 200, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.callNurseButton.setFont(font)
        self.callNurseButton.setObjectName("callNurseButton")
        self.stackedWidget.addWidget(self.callNursePage)
        self.scheduleNursePage = QtWidgets.QWidget()
        self.scheduleNursePage.setObjectName("scheduleNursePage")
        self.appointmentCalendar_3 = QtWidgets.QCalendarWidget(self.scheduleNursePage)
        self.appointmentCalendar_3.setGeometry(QtCore.QRect(590, 140, 312, 183))
        self.appointmentCalendar_3.setMinimumDate(QtCore.QDate(2020, 10, 3))
        self.appointmentCalendar_3.setGridVisible(False)
        self.appointmentCalendar_3.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.appointmentCalendar_3.setObjectName("appointmentCalendar_3")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.scheduleNursePage)
        self.timeEdit_3.setGeometry(QtCore.QRect(390, 290, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeEdit_3.setFont(font)
        self.timeEdit_3.setMaximumTime(QtCore.QTime(18, 0, 0))
        self.timeEdit_3.setMinimumTime(QtCore.QTime(8, 0, 0))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.scheduleNurseTitle = QtWidgets.QLabel(self.scheduleNursePage)
        self.scheduleNurseTitle.setGeometry(QtCore.QRect(20, 10, 911, 121))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.scheduleNurseTitle.setFont(font)
        self.scheduleNurseTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.scheduleNurseTitle.setObjectName("scheduleNurseTitle")
        self.typeAppointment_3 = QtWidgets.QLabel(self.scheduleNursePage)
        self.typeAppointment_3.setGeometry(QtCore.QRect(50, 130, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.typeAppointment_3.setFont(font)
        self.typeAppointment_3.setObjectName("typeAppointment_3")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.scheduleNursePage)
        self.dateEdit_3.setGeometry(QtCore.QRect(390, 220, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_3.setMinimumDate(QtCore.QDate(2020, 10, 3))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.appointmentTypeComboBox_3 = QtWidgets.QComboBox(self.scheduleNursePage)
        self.appointmentTypeComboBox_3.setGeometry(QtCore.QRect(390, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.appointmentTypeComboBox_3.setFont(font)
        self.appointmentTypeComboBox_3.setObjectName("appointmentTypeComboBox_3")
        self.appointmentTypeComboBox_3.addItem("")
        self.appointmentTypeComboBox_3.addItem("")
        self.appointmentTypeComboBox_3.addItem("")
        self.appointmentTypeComboBox_3.addItem("")
        self.timeSelectorLabel_3 = QtWidgets.QLabel(self.scheduleNursePage)
        self.timeSelectorLabel_3.setGeometry(QtCore.QRect(50, 270, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeSelectorLabel_3.setFont(font)
        self.timeSelectorLabel_3.setObjectName("timeSelectorLabel_3")
        self.cancelAppointmentButton_3 = QtWidgets.QPushButton(self.scheduleNursePage)
        self.cancelAppointmentButton_3.setGeometry(QtCore.QRect(120, 340, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cancelAppointmentButton_3.setFont(font)
        self.cancelAppointmentButton_3.setObjectName("cancelAppointmentButton_3")
        self.dateSelectorLabel_3 = QtWidgets.QLabel(self.scheduleNursePage)
        self.dateSelectorLabel_3.setGeometry(QtCore.QRect(50, 200, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dateSelectorLabel_3.setFont(font)
        self.dateSelectorLabel_3.setObjectName("dateSelectorLabel_3")
        self.acceptAppointmentButton_3 = QtWidgets.QPushButton(self.scheduleNursePage)
        self.acceptAppointmentButton_3.setGeometry(QtCore.QRect(350, 340, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.acceptAppointmentButton_3.setFont(font)
        self.acceptAppointmentButton_3.setObjectName("acceptAppointmentButton_3")
        self.stackedWidget.addWidget(self.scheduleNursePage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.appointmentTypeComboBox.setCurrentIndex(0)
        self.appointmentTypeComboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nursePushButton.setText(_translate("MainWindow", "Nurse Consult"))
        self.titleLabel.setText(_translate("MainWindow", "Medical Appointment Helper"))
        self.doctorPushButton.setText(_translate("MainWindow", "Doctor Consult"))
        self.contactInfoLabel.setText(_translate("MainWindow", "Enter your Contact Information"))
        self.firstNameLabel.setText(_translate("MainWindow", "First Name"))
        self.middleNameLabel.setText(_translate("MainWindow", "Middle Name"))
        self.lastNameLabel.setText(_translate("MainWindow", "Last Name"))
        self.phoneNumberLabel.setText(_translate("MainWindow", "Phone"))
        self.emailLabel.setText(_translate("MainWindow", "Email"))
        self.acceptInfoButton.setText(_translate("MainWindow", "Ok"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.insuranceInfoLabel.setText(_translate("MainWindow", "Enter your Insurance Information"))
        self.middleNameLabel_2.setText(_translate("MainWindow", "Middle Name"))
        self.firstNameLabel_2.setText(_translate("MainWindow", "First Name"))
        self.lastNameLabel_2.setText(_translate("MainWindow", "Last Name"))
        self.healthConcernsLabel.setText(_translate("MainWindow", "Select your symptoms"))
        self.fatigueCheckBox.setText(_translate("MainWindow", "Fatigue"))
        self.tightnessCheckBox.setText(_translate("MainWindow", "Tightness or pain in the chest, neck, back"))
        self.lightHeadedCheckBox.setText(_translate("MainWindow", "Light Headedness"))
        self.heartbeatCheckBox.setText(_translate("MainWindow", "Abnormal Heartbeat"))
        self.anxietyCheckBox.setText(_translate("MainWindow", "Anxiety"))
        self.otherCheckBox.setText(_translate("MainWindow", "Other"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.contactNurseLabel.setText(_translate("MainWindow", "Contact a Nurse"))
        self.nextAvailButton.setText(_translate("MainWindow", "Next Available Nurse"))
        self.scheduleACallButton.setText(_translate("MainWindow", "Schedule a Call with a Nurse"))
        self.scheduleTitle.setText(_translate("MainWindow", "Schedule a Doctor\'s Appointment"))
        self.typeAppointment.setText(_translate("MainWindow", "Select Appointment Type"))
        self.appointmentTypeComboBox.setCurrentText(_translate("MainWindow", "Select"))
        self.appointmentTypeComboBox.setItemText(0, _translate("MainWindow", "Select"))
        self.appointmentTypeComboBox.setItemText(1, _translate("MainWindow", "Physical"))
        self.appointmentTypeComboBox.setItemText(2, _translate("MainWindow", "Sick Visit"))
        self.appointmentTypeComboBox.setItemText(3, _translate("MainWindow", "Other"))
        self.dateSelectorLabel.setText(_translate("MainWindow", "Select Appointment Date"))
        self.timeSelectorLabel.setText(_translate("MainWindow", "Select Appointment Time"))
        self.acceptAppointmentButton.setText(_translate("MainWindow", "Ok"))
        self.cancelAppointmentButton.setText(_translate("MainWindow", "Cancel"))
        self.callNurseButton.setText(_translate("MainWindow", "Call Nurse"))
        self.scheduleNurseTitle.setText(_translate("MainWindow", "Schedule time to talk to Nurse"))
        self.typeAppointment_3.setText(_translate("MainWindow", "Select Appointment Type"))
        self.appointmentTypeComboBox_3.setCurrentText(_translate("MainWindow", "Select"))
        self.appointmentTypeComboBox_3.setItemText(0, _translate("MainWindow", "Select"))
        self.appointmentTypeComboBox_3.setItemText(1, _translate("MainWindow", "Physical"))
        self.appointmentTypeComboBox_3.setItemText(2, _translate("MainWindow", "Sick Visit"))
        self.appointmentTypeComboBox_3.setItemText(3, _translate("MainWindow", "Other"))
        self.timeSelectorLabel_3.setText(_translate("MainWindow", "Select Appointment Time"))
        self.cancelAppointmentButton_3.setText(_translate("MainWindow", "Cancel"))
        self.dateSelectorLabel_3.setText(_translate("MainWindow", "Select Appointment Date"))
        self.acceptAppointmentButton_3.setText(_translate("MainWindow", "Ok"))

